name: "Test the dart sass action"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dw-labs-org/dart-sass-gha@main
      - name: Run Dart Sass
        run: sass --version
        shell: bash
